# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import publishers.models.ad_spot


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0003_adspot_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='adspot',
            name='code',
            field=models.CharField(default=publishers.models.ad_spot.generate_unique_code, max_length=255, unique=True),
        ),
    ]
